USE customer;

SELECT * FROM mytable;


-- what is the total revenue generated by male vs female customers
SELECT sum(purchase_amount) , gender FROM mytable
GROUP BY gender;

-- which customer use discount but still spend more than avg purchse amount
SELECT purchase_amount, customer_id FROM mytable 
WHERE discount_applied = 'yes' AND purchase_amount >=  (SELECT avg(purchase_amount) FROM mytable);

-- which are the top 5 products with the highest avg review rating
SELECT item_purchased , round(avg(review_rating),2) AS avg_rating FROM mytable
GROUP BY item_purchased
ORDER BY avg_rating desc limit 5;

-- compare the avg purchase amounts between standard vs express shipping
SELECT ROUND(avg(purchase_amount),2) , shipping_type FROM mytable
WHERE shipping_type IN ('standard','express')
GROUP BY shipping_type;

-- do subscribed customers spent more? compare avg spend and total revenue between subscribers and non-subscribers
SELECT ROUND(avg(purchase_amount),2) AS avg_spend, sum(purchase_amount) AS total_revennue , subscription_status FROM mytable
GROUP BY subscription_status;

-- Which 5 products have the highest percentage of purchases when discount applied?
SELECT item_purchased,
ROUND(100 * sum(CASE WHEN discount_applied = 'yes' THEN 1 ELSE 0 END)/ COUNT(*),2) AS discount_rate
FROM mytable
GROUP BY item_purchased
ORDER BY discount_rate desc
limit 5;

-- segment customers into new, loyal, returning based on their previous purchases and show the count of each segment
WITH customer_type AS(
SELECT customer_id, previous_purchases,
CASE 
	WHEN previous_purchases = 1 THEN 'new'
	WHEN previous_purchases BETWEEN 2 AND 10 THEN 'returning'
	ELSE 'loyal'
	END AS customer_segment
FROM mytable
)

SELECT customer_segment, count(*) AS "number of customers"
FROM customer_type
GROUP BY customer_segment;

-- what are the top 3 most purchases products within each category
WITH item_count AS (
SELECT item_purchased,
 category,
 count(customer_id) AS total_orders,
 ROW_NUMBER() OVER(partition by category order by count(customer_id) desc ) as item_rank
 FROM mytable
 GROUP BY category, item_purchased
 )

SELECT item_rank , category, item_purchased , total_orders
FROM item_count
WHERE item_rank <= 3;

-- are customers who are repeated buyers ( more than 5 previous purchases ) also likely to subscribe ?
SELECT subscription_status,
count(customer_id) as total_customers
FROM mytable
WHERE previous_purchases >= 5
GROUP BY subscription_status;

-- what are the revenue contribution of each age group
SELECT age_group,
sum(purchase_amount) as total_revenue
FROM mytable
GROUP BY age_group
ORDER BY total_revenue desc;